services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasker_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:17
    container_name: tasker_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
